
// This file contains all the static Pokémon data for Gen 3.
// The main dataset `gbaTrainerDataset` is kept for advanced AI prompting.

// === TYPE EFFECTIVENESS CHART ===
export const typeChartData = {
  "Normal": { "Rock": 0.5, "Steel": 0.5, "Ghost": 0 },
  "Fire": { "Fire": 0.5, "Water": 0.5, "Grass": 2, "Ice": 2, "Bug": 2, "Rock": 0.5, "Dragon": 0.5, "Steel": 2 },
  "Water": { "Fire": 2, "Water": 0.5, "Grass": 0.5, "Ground": 2, "Rock": 2, "Dragon": 0.5 },
  "Electric": { "Water": 2, "Electric": 0.5, "Grass": 0.5, "Ground": 0, "Flying": 2, "Dragon": 0.5 },
  "Grass": { "Fire": 0.5, "Water": 2, "Grass": 0.5, "Poison": 0.5, "Ground": 2, "Flying": 0.5, "Bug": 0.5, "Rock": 2, "Dragon": 0.5, "Steel": 0.5 },
  "Ice": { "Fire": 0.5, "Water": 0.5, "Grass": 2, "Ice": 0.5, "Ground": 2, "Flying": 2, "Dragon": 2, "Steel": 0.5 },
  "Fighting": { "Normal": 2, "Ice": 2, "Poison": 0.5, "Flying": 0.5, "Psychic": 0.5, "Bug": 0.5, "Rock": 2, "Ghost": 0, "Dark": 2, "Steel": 2, "Fairy": 0.5 },
  "Poison": { "Grass": 2, "Poison": 0.5, "Ground": 0.5, "Rock": 0.5, "Ghost": 0.5, "Steel": 0, "Fairy": 2 },
  "Ground": { "Fire": 2, "Electric": 2, "Grass": 0.5, "Poison": 2, "Flying": 0, "Bug": 0.5, "Rock": 2, "Steel": 2 },
  "Flying": { "Electric": 0.5, "Grass": 2, "Fighting": 2, "Bug": 2, "Rock": 0.5, "Steel": 0.5 },
  "Psychic": { "Fighting": 2, "Poison": 2, "Psychic": 0.5, "Dark": 0, "Steel": 0.5 },
  "Bug": { "Fire": 0.5, "Grass": 2, "Fighting": 0.5, "Poison": 0.5, "Flying": 0.5, "Psychic": 2, "Ghost": 0.5, "Dark": 2, "Steel": 0.5, "Fairy": 0.5 },
  "Rock": { "Fire": 2, "Ice": 2, "Fighting": 0.5, "Ground": 0.5, "Flying": 2, "Bug": 2, "Steel": 0.5 },
  "Ghost": { "Normal": 0, "Psychic": 2, "Ghost": 2, "Dark": 0.5 },
  "Dragon": { "Dragon": 2, "Steel": 0.5, "Fairy": 0 },
  "Dark": { "Fighting": 0.5, "Psychic": 2, "Ghost": 2, "Dark": 0.5, "Fairy": 0.5 },
  "Steel": { "Fire": 0.5, "Water": 0.5, "Electric": 0.5, "Ice": 2, "Rock": 2, "Steel": 0.5, "Fairy": 2 },
  "Fairy": { "Fighting": 2, "Poison": 0.5, "Dragon": 2, "Dark": 2, "Steel": 0.5 }
};

// === POKEMON BASE DATA ===
// A selection of Gen 1-3 Pokémon for demonstration purposes.
export const pokemonData = {
  'bulbasaur': { dex_number: 1, types: ['Grass', 'Poison'], base_stats: { hp: 45, attack: 49, defense: 49, sp_attack: 65, sp_defense: 65, speed: 45 }, abilities: ['Overgrow'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png' },
  'ivysaur': { dex_number: 2, types: ['Grass', 'Poison'], base_stats: { hp: 60, attack: 62, defense: 63, sp_attack: 80, sp_defense: 80, speed: 60 }, abilities: ['Overgrow'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png' },
  'venusaur': { dex_number: 3, types: ['Grass', 'Poison'], base_stats: { hp: 80, attack: 82, defense: 83, sp_attack: 100, sp_defense: 100, speed: 80 }, abilities: ['Overgrow'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png' },
  'charmander': { dex_number: 4, types: ['Fire'], base_stats: { hp: 39, attack: 52, defense: 43, sp_attack: 60, sp_defense: 50, speed: 65 }, abilities: ['Blaze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png' },
  'charmeleon': { dex_number: 5, types: ['Fire'], base_stats: { hp: 58, attack: 64, defense: 58, sp_attack: 80, sp_defense: 65, speed: 80 }, abilities: ['Blaze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png' },
  'charizard': { dex_number: 6, types: ['Fire', 'Flying'], base_stats: { hp: 78, attack: 84, defense: 78, sp_attack: 109, sp_defense: 85, speed: 100 }, abilities: ['Blaze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png' },
  'squirtle': { dex_number: 7, types: ['Water'], base_stats: { hp: 44, attack: 48, defense: 65, sp_attack: 50, sp_defense: 64, speed: 43 }, abilities: ['Torrent'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png' },
  'wartortle': { dex_number: 8, types: ['Water'], base_stats: { hp: 59, attack: 63, defense: 80, sp_attack: 65, sp_defense: 80, speed: 58 }, abilities: ['Torrent'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png' },
  'blastoise': { dex_number: 9, types: ['Water'], base_stats: { hp: 79, attack: 83, defense: 100, sp_attack: 85, sp_defense: 105, speed: 78 }, abilities: ['Torrent'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png' },
  'caterpie': { dex_number: 10, types: ['Bug'], base_stats: { hp: 45, attack: 30, defense: 35, sp_attack: 20, sp_defense: 20, speed: 45 }, abilities: ['Shield Dust'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png' },
  'metapod': { dex_number: 11, types: ['Bug'], base_stats: { hp: 50, attack: 20, defense: 55, sp_attack: 25, sp_defense: 25, speed: 30 }, abilities: ['Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png' },
  'butterfree': { dex_number: 12, types: ['Bug', 'Flying'], base_stats: { hp: 60, attack: 45, defense: 50, sp_attack: 90, sp_defense: 80, speed: 70 }, abilities: ['Compound Eyes'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png' },
  'weedle': { dex_number: 13, types: ['Bug', 'Poison'], base_stats: { hp: 40, attack: 35, defense: 30, sp_attack: 20, sp_defense: 20, speed: 50 }, abilities: ['Shield Dust'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png' },
  'kakuna': { dex_number: 14, types: ['Bug', 'Poison'], base_stats: { hp: 45, attack: 25, defense: 50, sp_attack: 25, sp_defense: 25, speed: 35 }, abilities: ['Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png' },
  'beedrill': { dex_number: 15, types: ['Bug', 'Poison'], base_stats: { hp: 65, attack: 90, defense: 40, sp_attack: 45, sp_defense: 80, speed: 75 }, abilities: ['Swarm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png' },
  'pidgey': { dex_number: 16, types: ['Normal', 'Flying'], base_stats: { hp: 40, attack: 45, defense: 40, sp_attack: 35, sp_defense: 35, speed: 56 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png' },
  'pidgeotto': { dex_number: 17, types: ['Normal', 'Flying'], base_stats: { hp: 63, attack: 60, defense: 55, sp_attack: 50, sp_defense: 50, speed: 71 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png' },
  'pidgeot': { dex_number: 18, types: ['Normal', 'Flying'], base_stats: { hp: 83, attack: 80, defense: 75, sp_attack: 70, sp_defense: 70, speed: 101 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png' },
  'rattata': { dex_number: 19, types: ['Normal'], base_stats: { hp: 30, attack: 56, defense: 35, sp_attack: 25, sp_defense: 35, speed: 72 }, abilities: ['Run Away', 'Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png' },
  'raticate': { dex_number: 20, types: ['Normal'], base_stats: { hp: 55, attack: 81, defense: 60, sp_attack: 50, sp_defense: 70, speed: 97 }, abilities: ['Run Away', 'Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png' },
  'spearow': { dex_number: 21, types: ['Normal', 'Flying'], base_stats: { hp: 40, attack: 60, defense: 30, sp_attack: 31, sp_defense: 31, speed: 70 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png' },
  'fearow': { dex_number: 22, types: ['Normal', 'Flying'], base_stats: { hp: 65, attack: 90, defense: 65, sp_attack: 61, sp_defense: 61, speed: 100 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png' },
  'ekans': { dex_number: 23, types: ['Poison'], base_stats: { hp: 35, attack: 60, defense: 44, sp_attack: 40, sp_defense: 54, speed: 55 }, abilities: ['Intimidate', 'Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png' },
  'arbok': { dex_number: 24, types: ['Poison'], base_stats: { hp: 60, attack: 95, defense: 69, sp_attack: 65, sp_defense: 79, speed: 80 }, abilities: ['Intimidate', 'Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png' },
  'pikachu': { dex_number: 25, types: ['Electric'], base_stats: { hp: 35, attack: 55, defense: 40, sp_attack: 50, sp_defense: 50, speed: 90 }, abilities: ['Static'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png' },
  'raichu': { dex_number: 26, types: ['Electric'], base_stats: { hp: 60, attack: 90, defense: 55, sp_attack: 90, sp_defense: 80, speed: 110 }, abilities: ['Static'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png' },
  'sandshrew': { dex_number: 27, types: ['Ground'], base_stats: { hp: 50, attack: 75, defense: 85, sp_attack: 20, sp_defense: 30, speed: 40 }, abilities: ['Sand Veil'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png' },
  'sandslash': { dex_number: 28, types: ['Ground'], base_stats: { hp: 75, attack: 100, defense: 110, sp_attack: 45, sp_defense: 55, speed: 65 }, abilities: ['Sand Veil'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png' },
  'nidoran-f': { dex_number: 29, types: ['Poison'], base_stats: { hp: 55, attack: 47, defense: 52, sp_attack: 40, sp_defense: 40, speed: 41 }, abilities: ['Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png' },
  'nidorina': { dex_number: 30, types: ['Poison'], base_stats: { hp: 70, attack: 62, defense: 67, sp_attack: 55, sp_defense: 55, speed: 56 }, abilities: ['Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png' },
  'nidoqueen': { dex_number: 31, types: ['Poison', 'Ground'], base_stats: { hp: 90, attack: 92, defense: 87, sp_attack: 75, sp_defense: 85, speed: 76 }, abilities: ['Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png' },
  'nidoran-m': { dex_number: 32, types: ['Poison'], base_stats: { hp: 46, attack: 57, defense: 40, sp_attack: 40, sp_defense: 40, speed: 50 }, abilities: ['Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png' },
  'nidorino': { dex_number: 33, types: ['Poison'], base_stats: { hp: 61, attack: 72, defense: 57, sp_attack: 55, sp_defense: 55, speed: 65 }, abilities: ['Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png' },
  'nidoking': { dex_number: 34, types: ['Poison', 'Ground'], base_stats: { hp: 81, attack: 102, defense: 77, sp_attack: 85, sp_defense: 75, speed: 85 }, abilities: ['Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png' },
  'clefairy': { dex_number: 35, types: ['Fairy'], base_stats: { hp: 70, attack: 45, defense: 48, sp_attack: 60, sp_defense: 65, speed: 35 }, abilities: ['Cute Charm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png' },
  'clefable': { dex_number: 36, types: ['Fairy'], base_stats: { hp: 95, attack: 70, defense: 73, sp_attack: 95, sp_defense: 90, speed: 60 }, abilities: ['Cute Charm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png' },
  'vulpix': { dex_number: 37, types: ['Fire'], base_stats: { hp: 38, attack: 41, defense: 40, sp_attack: 50, sp_defense: 65, speed: 65 }, abilities: ['Flash Fire'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png' },
  'ninetales': { dex_number: 38, types: ['Fire'], base_stats: { hp: 73, attack: 76, defense: 75, sp_attack: 81, sp_defense: 100, speed: 100 }, abilities: ['Flash Fire'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png' },
  'jigglypuff': { dex_number: 39, types: ['Normal', 'Fairy'], base_stats: { hp: 115, attack: 45, defense: 20, sp_attack: 45, sp_defense: 25, speed: 20 }, abilities: ['Cute Charm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png' },
  'wigglytuff': { dex_number: 40, types: ['Normal', 'Fairy'], base_stats: { hp: 140, attack: 70, defense: 45, sp_attack: 85, sp_defense: 50, speed: 45 }, abilities: ['Cute Charm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png' },
  'zubat': { dex_number: 41, types: ['Poison', 'Flying'], base_stats: { hp: 40, attack: 45, defense: 35, sp_attack: 30, sp_defense: 40, speed: 55 }, abilities: ['Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png' },
  'golbat': { dex_number: 42, types: ['Poison', 'Flying'], base_stats: { hp: 75, attack: 80, defense: 70, sp_attack: 65, sp_defense: 75, speed: 90 }, abilities: ['Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png' },
  'oddish': { dex_number: 43, types: ['Grass', 'Poison'], base_stats: { hp: 45, attack: 50, defense: 55, sp_attack: 75, sp_defense: 65, speed: 30 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png' },
  'gloom': { dex_number: 44, types: ['Grass', 'Poison'], base_stats: { hp: 60, attack: 65, defense: 70, sp_attack: 85, sp_defense: 75, speed: 40 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png' },
  'vileplume': { dex_number: 45, types: ['Grass', 'Poison'], base_stats: { hp: 75, attack: 80, defense: 85, sp_attack: 110, sp_defense: 90, speed: 50 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png' },
  'paras': { dex_number: 46, types: ['Bug', 'Grass'], base_stats: { hp: 35, attack: 70, defense: 55, sp_attack: 45, sp_defense: 55, speed: 25 }, abilities: ['Effect Spore'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png' },
  'parasect': { dex_number: 47, types: ['Bug', 'Grass'], base_stats: { hp: 60, attack: 95, defense: 80, sp_attack: 60, sp_defense: 80, speed: 30 }, abilities: ['Effect Spore'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png' },
  'venonat': { dex_number: 48, types: ['Bug', 'Poison'], base_stats: { hp: 60, attack: 55, defense: 50, sp_attack: 40, sp_defense: 55, speed: 45 }, abilities: ['Compound Eyes'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png' },
  'venomoth': { dex_number: 49, types: ['Bug', 'Poison'], base_stats: { hp: 70, attack: 65, defense: 60, sp_attack: 90, sp_defense: 75, speed: 90 }, abilities: ['Shield Dust'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png' },
  'diglett': { dex_number: 50, types: ['Ground'], base_stats: { hp: 10, attack: 55, defense: 25, sp_attack: 35, sp_defense: 45, speed: 95 }, abilities: ['Sand Veil', 'Arena Trap'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png' },
  'dugtrio': { dex_number: 51, types: ['Ground'], base_stats: { hp: 35, attack: 100, defense: 50, sp_attack: 50, sp_defense: 70, speed: 120 }, abilities: ['Sand Veil', 'Arena Trap'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png' },
  'meowth': { dex_number: 52, types: ['Normal'], base_stats: { hp: 40, attack: 45, defense: 35, sp_attack: 40, sp_defense: 40, speed: 90 }, abilities: ['Pickup'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png' },
  'persian': { dex_number: 53, types: ['Normal'], base_stats: { hp: 65, attack: 70, defense: 60, sp_attack: 65, sp_defense: 65, speed: 115 }, abilities: ['Limber'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png' },
  'psyduck': { dex_number: 54, types: ['Water'], base_stats: { hp: 50, attack: 52, defense: 48, sp_attack: 65, sp_defense: 50, speed: 55 }, abilities: ['Damp', 'Cloud Nine'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png' },
  'golduck': { dex_number: 55, types: ['Water'], base_stats: { hp: 80, attack: 82, defense: 78, sp_attack: 95, sp_defense: 80, speed: 85 }, abilities: ['Damp', 'Cloud Nine'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png' },
  'mankey': { dex_number: 56, types: ['Fighting'], base_stats: { hp: 40, attack: 80, defense: 35, sp_attack: 35, sp_defense: 45, speed: 70 }, abilities: ['Vital Spirit'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png' },
  'primeape': { dex_number: 57, types: ['Fighting'], base_stats: { hp: 65, attack: 105, defense: 60, sp_attack: 60, sp_defense: 70, speed: 95 }, abilities: ['Vital Spirit'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png' },
  'growlithe': { dex_number: 58, types: ['Fire'], base_stats: { hp: 55, attack: 70, defense: 45, sp_attack: 70, sp_defense: 50, speed: 60 }, abilities: ['Intimidate', 'Flash Fire'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png' },
  'arcanine': { dex_number: 59, types: ['Fire'], base_stats: { hp: 90, attack: 110, defense: 80, sp_attack: 100, sp_defense: 80, speed: 95 }, abilities: ['Intimidate', 'Flash Fire'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png' },
  'poliwag': { dex_number: 60, types: ['Water'], base_stats: { hp: 40, attack: 50, defense: 40, sp_attack: 40, sp_defense: 40, speed: 90 }, abilities: ['Water Absorb', 'Damp'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png' },
  'poliwhirl': { dex_number: 61, types: ['Water'], base_stats: { hp: 65, attack: 65, defense: 65, sp_attack: 50, sp_defense: 50, speed: 90 }, abilities: ['Water Absorb', 'Damp'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png' },
  'poliwrath': { dex_number: 62, types: ['Water', 'Fighting'], base_stats: { hp: 90, attack: 95, defense: 95, sp_attack: 70, sp_defense: 90, speed: 70 }, abilities: ['Water Absorb', 'Damp'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png' },
  'abra': { dex_number: 63, types: ['Psychic'], base_stats: { hp: 25, attack: 20, defense: 15, sp_attack: 105, sp_defense: 55, speed: 90 }, abilities: ['Synchronize', 'Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png' },
  'kadabra': { dex_number: 64, types: ['Psychic'], base_stats: { hp: 40, attack: 35, defense: 30, sp_attack: 120, sp_defense: 70, speed: 105 }, abilities: ['Synchronize', 'Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png' },
  'alakazam': { dex_number: 65, types: ['Psychic'], base_stats: { hp: 55, attack: 50, defense: 45, sp_attack: 135, sp_defense: 95, speed: 120 }, abilities: ['Synchronize', 'Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png' },
  'machop': { dex_number: 66, types: ['Fighting'], base_stats: { hp: 70, attack: 80, defense: 50, sp_attack: 35, sp_defense: 35, speed: 35 }, abilities: ['Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png' },
  'machoke': { dex_number: 67, types: ['Fighting'], base_stats: { hp: 80, attack: 100, defense: 70, sp_attack: 50, sp_defense: 60, speed: 45 }, abilities: ['Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png' },
  'machamp': { dex_number: 68, types: ['Fighting'], base_stats: { hp: 90, attack: 130, defense: 80, sp_attack: 65, sp_defense: 85, speed: 55 }, abilities: ['Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png' },
  'bellsprout': { dex_number: 69, types: ['Grass', 'Poison'], base_stats: { hp: 50, attack: 75, defense: 35, sp_attack: 70, sp_defense: 30, speed: 40 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png' },
  'weepinbell': { dex_number: 70, types: ['Grass', 'Poison'], base_stats: { hp: 65, attack: 90, defense: 50, sp_attack: 85, sp_defense: 45, speed: 55 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png' },
  'victreebel': { dex_number: 71, types: ['Grass', 'Poison'], base_stats: { hp: 80, attack: 105, defense: 65, sp_attack: 100, sp_defense: 70, speed: 70 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png' },
  'tentacool': { dex_number: 72, types: ['Water', 'Poison'], base_stats: { hp: 40, attack: 40, defense: 35, sp_attack: 50, sp_defense: 100, speed: 70 }, abilities: ['Clear Body', 'Liquid Ooze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png' },
  'tentacruel': { dex_number: 73, types: ['Water', 'Poison'], base_stats: { hp: 80, attack: 70, defense: 65, sp_attack: 80, sp_defense: 120, speed: 100 }, abilities: ['Clear Body', 'Liquid Ooze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png' },
  'geodude': { dex_number: 74, types: ['Rock', 'Ground'], base_stats: { hp: 40, attack: 80, defense: 100, sp_attack: 30, sp_defense: 30, speed: 20 }, abilities: ['Rock Head', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png' },
  'graveler': { dex_number: 75, types: ['Rock', 'Ground'], base_stats: { hp: 55, attack: 95, defense: 115, sp_attack: 45, sp_defense: 45, speed: 35 }, abilities: ['Rock Head', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png' },
  'golem': { dex_number: 76, types: ['Rock', 'Ground'], base_stats: { hp: 80, attack: 120, defense: 130, sp_attack: 55, sp_defense: 65, speed: 45 }, abilities: ['Rock Head', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png' },
  'ponyta': { dex_number: 77, types: ['Fire'], base_stats: { hp: 50, attack: 85, defense: 55, sp_attack: 65, sp_defense: 65, speed: 90 }, abilities: ['Run Away', 'Flash Fire'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png' },
  'rapidash': { dex_number: 78, types: ['Fire'], base_stats: { hp: 65, attack: 100, defense: 70, sp_attack: 80, sp_defense: 80, speed: 105 }, abilities: ['Run Away', 'Flash Fire'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png' },
  'slowpoke': { dex_number: 79, types: ['Water', 'Psychic'], base_stats: { hp: 90, attack: 65, defense: 65, sp_attack: 40, sp_defense: 40, speed: 15 }, abilities: ['Oblivious', 'Own Tempo'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png' },
  'slowbro': { dex_number: 80, types: ['Water', 'Psychic'], base_stats: { hp: 95, attack: 75, defense: 110, sp_attack: 100, sp_defense: 80, speed: 30 }, abilities: ['Oblivious', 'Own Tempo'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png' },
  'magnemite': { dex_number: 81, types: ['Electric', 'Steel'], base_stats: { hp: 25, attack: 35, defense: 70, sp_attack: 95, sp_defense: 55, speed: 45 }, abilities: ['Magnet Pull', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png' },
  'magneton': { dex_number: 82, types: ['Electric', 'Steel'], base_stats: { hp: 50, attack: 60, defense: 95, sp_attack: 120, sp_defense: 70, speed: 70 }, abilities: ['Magnet Pull', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png' },
  'farfetchd': { dex_number: 83, types: ['Normal', 'Flying'], base_stats: { hp: 52, attack: 90, defense: 55, sp_attack: 58, sp_defense: 62, speed: 60 }, abilities: ['Keen Eye', 'Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png' },
  'doduo': { dex_number: 84, types: ['Normal', 'Flying'], base_stats: { hp: 35, attack: 85, defense: 45, sp_attack: 35, sp_defense: 35, speed: 75 }, abilities: ['Run Away', 'Early Bird'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png' },
  'dodrio': { dex_number: 85, types: ['Normal', 'Flying'], base_stats: { hp: 60, attack: 110, defense: 70, sp_attack: 60, sp_defense: 60, speed: 110 }, abilities: ['Run Away', 'Early Bird'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png' },
  'seel': { dex_number: 86, types: ['Water'], base_stats: { hp: 65, attack: 45, defense: 55, sp_attack: 45, sp_defense: 70, speed: 45 }, abilities: ['Thick Fat'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png' },
  'dewgong': { dex_number: 87, types: ['Water', 'Ice'], base_stats: { hp: 90, attack: 70, defense: 80, sp_attack: 70, sp_defense: 95, speed: 70 }, abilities: ['Thick Fat'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png' },
  'grimer': { dex_number: 88, types: ['Poison'], base_stats: { hp: 80, attack: 80, defense: 50, sp_attack: 40, sp_defense: 50, speed: 25 }, abilities: ['Stench', 'Sticky Hold'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png' },
  'muk': { dex_number: 89, types: ['Poison'], base_stats: { hp: 105, attack: 105, defense: 75, sp_attack: 65, sp_defense: 100, speed: 50 }, abilities: ['Stench', 'Sticky Hold'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png' },
  'shellder': { dex_number: 90, types: ['Water'], base_stats: { hp: 30, attack: 65, defense: 100, sp_attack: 45, sp_defense: 25, speed: 40 }, abilities: ['Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png' },
  'cloyster': { dex_number: 91, types: ['Water', 'Ice'], base_stats: { hp: 50, attack: 95, defense: 180, sp_attack: 85, sp_defense: 45, speed: 70 }, abilities: ['Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png' },
  'gastly': { dex_number: 92, types: ['Ghost', 'Poison'], base_stats: { hp: 30, attack: 35, defense: 30, sp_attack: 100, sp_defense: 35, speed: 80 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png' },
  'haunter': { dex_number: 93, types: ['Ghost', 'Poison'], base_stats: { hp: 45, attack: 50, defense: 45, sp_attack: 115, sp_defense: 55, speed: 95 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png' },
  'gengar': { dex_number: 94, types: ['Ghost', 'Poison'], base_stats: { hp: 60, attack: 65, defense: 60, sp_attack: 130, sp_defense: 75, speed: 110 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png' },
  'onix': { dex_number: 95, types: ['Rock', 'Ground'], base_stats: { hp: 35, attack: 45, defense: 160, sp_attack: 30, sp_defense: 45, speed: 70 }, abilities: ['Rock Head', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png' },
  'drowzee': { dex_number: 96, types: ['Psychic'], base_stats: { hp: 60, attack: 48, defense: 45, sp_attack: 43, sp_defense: 90, speed: 42 }, abilities: ['Insomnia', 'Forewarn'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png' },
  'hypno': { dex_number: 97, types: ['Psychic'], base_stats: { hp: 85, attack: 73, defense: 70, sp_attack: 73, sp_defense: 115, speed: 67 }, abilities: ['Insomnia', 'Forewarn'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png' },
  'krabby': { dex_number: 98, types: ['Water'], base_stats: { hp: 30, attack: 105, defense: 90, sp_attack: 25, sp_defense: 25, speed: 50 }, abilities: ['Hyper Cutter', 'Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png' },
  'kingler': { dex_number: 99, types: ['Water'], base_stats: { hp: 55, attack: 130, defense: 115, sp_attack: 50, sp_defense: 50, speed: 75 }, abilities: ['Hyper Cutter', 'Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png' },
  'voltorb': { dex_number: 100, types: ['Electric'], base_stats: { hp: 40, attack: 30, defense: 50, sp_attack: 55, sp_defense: 55, speed: 100 }, abilities: ['Soundproof', 'Static'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png' },
  'electrode': { dex_number: 101, types: ['Electric'], base_stats: { hp: 60, attack: 50, defense: 70, sp_attack: 80, sp_defense: 80, speed: 150 }, abilities: ['Soundproof', 'Static'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png' },
  'exeggcute': { dex_number: 102, types: ['Grass', 'Psychic'], base_stats: { hp: 60, attack: 40, defense: 80, sp_attack: 60, sp_defense: 45, speed: 40 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png' },
  'exeggutor': { dex_number: 103, types: ['Grass', 'Psychic'], base_stats: { hp: 95, attack: 95, defense: 85, sp_attack: 125, sp_defense: 75, speed: 55 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png' },
  'cubone': { dex_number: 104, types: ['Ground'], base_stats: { hp: 50, attack: 50, defense: 95, sp_attack: 40, sp_defense: 50, speed: 35 }, abilities: ['Rock Head', 'Lightning Rod'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png' },
  'marowak': { dex_number: 105, types: ['Ground'], base_stats: { hp: 60, attack: 80, defense: 110, sp_attack: 50, sp_defense: 80, speed: 45 }, abilities: ['Rock Head', 'Lightning Rod'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png' },
  'snorlax': { dex_number: 143, types: ['Normal'], base_stats: { hp: 160, attack: 110, defense: 65, sp_attack: 65, sp_defense: 110, speed: 30 }, abilities: ['Immunity', 'Thick Fat'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png' },
  'crobat': { dex_number: 169, types: ['Poison', 'Flying'], base_stats: { hp: 85, attack: 90, defense: 80, sp_attack: 70, sp_defense: 80, speed: 130 }, abilities: ['Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/169.png' },
  'heracross': { dex_number: 214, types: ['Bug', 'Fighting'], base_stats: { hp: 80, attack: 125, defense: 75, sp_attack: 40, sp_defense: 95, speed: 85 }, abilities: ['Swarm', 'Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/214.png' },
  'skarmory': { dex_number: 227, types: ['Steel', 'Flying'], base_stats: { hp: 65, attack: 80, defense: 140, sp_attack: 40, sp_defense: 70, speed: 70 }, abilities: ['Keen Eye', 'Sturdy'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png' },
  'tyranitar': { dex_number: 248, types: ['Rock', 'Dark'], base_stats: { hp: 100, attack: 134, defense: 110, sp_attack: 95, sp_defense: 100, speed: 61 }, abilities: ['Sand Stream'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png' },
  'treecko': { dex_number: 252, types: ['Grass'], base_stats: { hp: 40, attack: 45, defense: 35, sp_attack: 65, sp_defense: 55, speed: 70 }, abilities: ['Overgrow'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/252.png' },
  'grovyle': { dex_number: 253, types: ['Grass'], base_stats: { hp: 50, attack: 65, defense: 45, sp_attack: 85, sp_defense: 65, speed: 95 }, abilities: ['Overgrow'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/253.png' },
  'sceptile': { dex_number: 254, types: ['Grass'], base_stats: { hp: 70, attack: 85, defense: 65, sp_attack: 105, sp_defense: 85, speed: 120 }, abilities: ['Overgrow'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/254.png' },
  'torchic': { dex_number: 255, types: ['Fire'], base_stats: { hp: 45, attack: 60, defense: 40, sp_attack: 70, sp_defense: 50, speed: 45 }, abilities: ['Blaze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png' },
  'combusken': { dex_number: 256, types: ['Fire', 'Fighting'], base_stats: { hp: 60, attack: 85, defense: 60, sp_attack: 85, sp_defense: 60, speed: 55 }, abilities: ['Blaze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/256.png' },
  'blaziken': { dex_number: 257, types: ['Fire', 'Fighting'], base_stats: { hp: 80, attack: 120, defense: 70, sp_attack: 110, sp_defense: 70, speed: 80 }, abilities: ['Blaze'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/257.png' },
  'mudkip': { dex_number: 258, types: ['Water'], base_stats: { hp: 50, attack: 70, defense: 50, sp_attack: 50, sp_defense: 50, speed: 40 }, abilities: ['Torrent'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png' },
  'marshtomp': { dex_number: 259, types: ['Water', 'Ground'], base_stats: { hp: 70, attack: 85, defense: 70, sp_attack: 60, sp_defense: 70, speed: 50 }, abilities: ['Torrent'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/259.png' },
  'swampert': { dex_number: 260, types: ['Water', 'Ground'], base_stats: { hp: 100, attack: 110, defense: 90, sp_attack: 85, sp_defense: 90, speed: 60 }, abilities: ['Torrent'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png' },
  'poochyena': { dex_number: 261, types: ['Dark'], base_stats: { hp: 35, attack: 55, defense: 35, sp_attack: 30, sp_defense: 30, speed: 35 }, abilities: ['Run Away', 'Intimidate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/261.png' },
  'mightyena': { dex_number: 262, types: ['Dark'], base_stats: { hp: 70, attack: 90, defense: 70, sp_attack: 60, sp_defense: 60, speed: 70 }, abilities: ['Intimidate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/262.png' },
  'zigzagoon': { dex_number: 263, types: ['Normal'], base_stats: { hp: 38, attack: 30, defense: 41, sp_attack: 30, sp_defense: 41, speed: 60 }, abilities: ['Pickup'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/263.png' },
  'linoone': { dex_number: 264, types: ['Normal'], base_stats: { hp: 78, attack: 70, defense: 61, sp_attack: 50, sp_defense: 61, speed: 100 }, abilities: ['Pickup'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/264.png' },
  'wurmple': { dex_number: 265, types: ['Bug'], base_stats: { hp: 45, attack: 45, defense: 35, sp_attack: 20, sp_defense: 30, speed: 20 }, abilities: ['Shield Dust'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/265.png' },
  'silcoon': { dex_number: 266, types: ['Bug'], base_stats: { hp: 50, attack: 35, defense: 55, sp_attack: 25, sp_defense: 25, speed: 15 }, abilities: ['Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/266.png' },
  'beautifly': { dex_number: 267, types: ['Bug', 'Flying'], base_stats: { hp: 60, attack: 70, defense: 50, sp_attack: 100, sp_defense: 50, speed: 65 }, abilities: ['Swarm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/267.png' },
  'cascoon': { dex_number: 268, types: ['Bug'], base_stats: { hp: 50, attack: 35, defense: 55, sp_attack: 25, sp_defense: 25, speed: 15 }, abilities: ['Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/268.png' },
  'dustox': { dex_number: 269, types: ['Bug', 'Poison'], base_stats: { hp: 60, attack: 50, defense: 70, sp_attack: 50, sp_defense: 90, speed: 65 }, abilities: ['Shield Dust'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/269.png' },
  'lotad': { dex_number: 270, types: ['Water', 'Grass'], base_stats: { hp: 40, attack: 30, defense: 30, sp_attack: 40, sp_defense: 50, speed: 30 }, abilities: ['Swift Swim', 'Rain Dish'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/270.png' },
  'lombre': { dex_number: 271, types: ['Water', 'Grass'], base_stats: { hp: 60, attack: 50, defense: 50, sp_attack: 60, sp_defense: 70, speed: 50 }, abilities: ['Swift Swim', 'Rain Dish'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/271.png' },
  'ludicolo': { dex_number: 272, types: ['Water', 'Grass'], base_stats: { hp: 80, attack: 70, defense: 70, sp_attack: 90, sp_defense: 100, speed: 70 }, abilities: ['Swift Swim', 'Rain Dish'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/272.png' },
  'seedot': { dex_number: 273, types: ['Grass'], base_stats: { hp: 40, attack: 40, defense: 50, sp_attack: 30, sp_defense: 30, speed: 30 }, abilities: ['Chlorophyll', 'Early Bird'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/273.png' },
  'nuzleaf': { dex_number: 274, types: ['Grass', 'Dark'], base_stats: { hp: 70, attack: 70, defense: 40, sp_attack: 60, sp_defense: 40, speed: 60 }, abilities: ['Chlorophyll', 'Early Bird'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/274.png' },
  'shiftry': { dex_number: 275, types: ['Grass', 'Dark'], base_stats: { hp: 90, attack: 100, defense: 60, sp_attack: 90, sp_defense: 60, speed: 80 }, abilities: ['Chlorophyll', 'Early Bird'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/275.png' },
  'taillow': { dex_number: 276, types: ['Normal', 'Flying'], base_stats: { hp: 40, attack: 55, defense: 30, sp_attack: 30, sp_defense: 30, speed: 85 }, abilities: ['Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/276.png' },
  'swellow': { dex_number: 277, types: ['Normal', 'Flying'], base_stats: { hp: 60, attack: 85, defense: 60, sp_attack: 75, sp_defense: 50, speed: 125 }, abilities: ['Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/277.png' },
  'wingull': { dex_number: 278, types: ['Water', 'Flying'], base_stats: { hp: 40, attack: 30, defense: 30, sp_attack: 55, sp_defense: 30, speed: 85 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/278.png' },
  'pelipper': { dex_number: 279, types: ['Water', 'Flying'], base_stats: { hp: 60, attack: 50, defense: 100, sp_attack: 95, sp_defense: 70, speed: 65 }, abilities: ['Keen Eye', 'Drizzle'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/279.png' },
  'ralts': { dex_number: 280, types: ['Psychic', 'Fairy'], base_stats: { hp: 28, attack: 25, defense: 25, sp_attack: 45, sp_defense: 35, speed: 40 }, abilities: ['Synchronize', 'Trace'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/280.png' },
  'kirlia': { dex_number: 281, types: ['Psychic', 'Fairy'], base_stats: { hp: 38, attack: 35, defense: 35, sp_attack: 65, sp_defense: 55, speed: 50 }, abilities: ['Synchronize', 'Trace'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/281.png' },
  'gardevoir': { dex_number: 282, types: ['Psychic', 'Fairy'], base_stats: { hp: 68, attack: 65, defense: 65, sp_attack: 125, sp_defense: 115, speed: 80 }, abilities: ['Synchronize', 'Trace'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png' },
  'surskit': { dex_number: 283, types: ['Bug', 'Water'], base_stats: { hp: 40, attack: 30, defense: 32, sp_attack: 50, sp_defense: 52, speed: 65 }, abilities: ['Swift Swim'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/283.png' },
  'masquerain': { dex_number: 284, types: ['Bug', 'Flying'], base_stats: { hp: 70, attack: 60, defense: 62, sp_attack: 100, sp_defense: 82, speed: 80 }, abilities: ['Intimidate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/284.png' },
  'shroomish': { dex_number: 285, types: ['Grass'], base_stats: { hp: 60, attack: 40, defense: 60, sp_attack: 40, sp_defense: 60, speed: 35 }, abilities: ['Effect Spore'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/285.png' },
  'breloom': { dex_number: 286, types: ['Grass', 'Fighting'], base_stats: { hp: 60, attack: 130, defense: 80, sp_attack: 60, sp_defense: 60, speed: 70 }, abilities: ['Effect Spore'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/286.png' },
  'slakoth': { dex_number: 287, types: ['Normal'], base_stats: { hp: 60, attack: 60, defense: 60, sp_attack: 35, sp_defense: 35, speed: 30 }, abilities: ['Truant'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/287.png' },
  'vigoroth': { dex_number: 288, types: ['Normal'], base_stats: { hp: 80, attack: 80, defense: 80, sp_attack: 55, sp_defense: 55, speed: 90 }, abilities: ['Vital Spirit'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/288.png' },
  'slaking': { dex_number: 289, types: ['Normal'], base_stats: { hp: 150, attack: 160, defense: 100, sp_attack: 95, sp_defense: 65, speed: 100 }, abilities: ['Truant'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/289.png' },
  'nincada': { dex_number: 290, types: ['Bug', 'Ground'], base_stats: { hp: 31, attack: 45, defense: 90, sp_attack: 30, sp_defense: 30, speed: 40 }, abilities: ['Compound Eyes'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/290.png' },
  'ninjask': { dex_number: 291, types: ['Bug', 'Flying'], base_stats: { hp: 61, attack: 90, defense: 45, sp_attack: 50, sp_defense: 50, speed: 160 }, abilities: ['Speed Boost'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/291.png' },
  'shedinja': { dex_number: 292, types: ['Bug', 'Ghost'], base_stats: { hp: 1, attack: 90, defense: 45, sp_attack: 30, sp_defense: 30, speed: 40 }, abilities: ['Wonder Guard'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/292.png' },
  'whismur': { dex_number: 293, types: ['Normal'], base_stats: { hp: 64, attack: 51, defense: 23, sp_attack: 51, sp_defense: 23, speed: 28 }, abilities: ['Soundproof'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/293.png' },
  'loudred': { dex_number: 294, types: ['Normal'], base_stats: { hp: 84, attack: 71, defense: 43, sp_attack: 71, sp_defense: 43, speed: 48 }, abilities: ['Soundproof'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/294.png' },
  'exploud': { dex_number: 295, types: ['Normal'], base_stats: { hp: 104, attack: 91, defense: 63, sp_attack: 91, sp_defense: 73, speed: 68 }, abilities: ['Soundproof'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/295.png' },
  'makuhita': { dex_number: 296, types: ['Fighting'], base_stats: { hp: 72, attack: 60, defense: 30, sp_attack: 20, sp_defense: 30, speed: 25 }, abilities: ['Thick Fat', 'Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/296.png' },
  'hariyama': { dex_number: 297, types: ['Fighting'], base_stats: { hp: 144, attack: 120, defense: 60, sp_attack: 40, sp_defense: 60, speed: 50 }, abilities: ['Thick Fat', 'Guts'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/297.png' },
  'azurill': { dex_number: 298, types: ['Normal', 'Fairy'], base_stats: { hp: 50, attack: 20, defense: 40, sp_attack: 20, sp_defense: 40, speed: 20 }, abilities: ['Thick Fat', 'Huge Power'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/298.png' },
  'nosepass': { dex_number: 299, types: ['Rock'], base_stats: { hp: 30, attack: 45, defense: 135, sp_attack: 45, sp_defense: 90, speed: 30 }, abilities: ['Sturdy', 'Magnet Pull'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/299.png' },
  'skitty': { dex_number: 300, types: ['Normal'], base_stats: { hp: 50, attack: 45, defense: 45, sp_attack: 35, sp_defense: 35, speed: 50 }, abilities: ['Cute Charm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/300.png' },
  'delcatty': { dex_number: 301, types: ['Normal'], base_stats: { hp: 70, attack: 65, defense: 65, sp_attack: 55, sp_defense: 55, speed: 90 }, abilities: ['Cute Charm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/301.png' },
  'sableye': { dex_number: 302, types: ['Dark', 'Ghost'], base_stats: { hp: 50, attack: 75, defense: 75, sp_attack: 65, sp_defense: 65, speed: 50 }, abilities: ['Keen Eye'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/302.png' },
  'mawile': { dex_number: 303, types: ['Steel', 'Fairy'], base_stats: { hp: 50, attack: 85, defense: 85, sp_attack: 55, sp_defense: 55, speed: 50 }, abilities: ['Hyper Cutter', 'Intimidate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/303.png' },
  'aron': { dex_number: 304, types: ['Steel', 'Rock'], base_stats: { hp: 50, attack: 70, defense: 100, sp_attack: 40, sp_defense: 40, speed: 30 }, abilities: ['Sturdy', 'Rock Head'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/304.png' },
  'lairon': { dex_number: 305, types: ['Steel', 'Rock'], base_stats: { hp: 60, attack: 90, defense: 140, sp_attack: 50, sp_defense: 50, speed: 40 }, abilities: ['Sturdy', 'Rock Head'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/305.png' },
  'aggron': { dex_number: 306, types: ['Steel', 'Rock'], base_stats: { hp: 70, attack: 110, defense: 180, sp_attack: 60, sp_defense: 60, speed: 50 }, abilities: ['Sturdy', 'Rock Head'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/306.png' },
  'meditite': { dex_number: 307, types: ['Fighting', 'Psychic'], base_stats: { hp: 30, attack: 40, defense: 55, sp_attack: 40, sp_defense: 55, speed: 60 }, abilities: ['Pure Power'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/307.png' },
  'medicham': { dex_number: 308, types: ['Fighting', 'Psychic'], base_stats: { hp: 60, attack: 60, defense: 75, sp_attack: 60, sp_defense: 75, speed: 80 }, abilities: ['Pure Power'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/308.png' },
  'electrike': { dex_number: 309, types: ['Electric'], base_stats: { hp: 40, attack: 45, defense: 40, sp_attack: 65, sp_defense: 40, speed: 65 }, abilities: ['Static', 'Lightning Rod'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/309.png' },
  'manectric': { dex_number: 310, types: ['Electric'], base_stats: { hp: 70, attack: 75, defense: 60, sp_attack: 105, sp_defense: 60, speed: 105 }, abilities: ['Static', 'Lightning Rod'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/310.png' },
  'plusle': { dex_number: 311, types: ['Electric'], base_stats: { hp: 60, attack: 50, defense: 40, sp_attack: 85, sp_defense: 75, speed: 95 }, abilities: ['Plus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/311.png' },
  'minun': { dex_number: 312, types: ['Electric'], base_stats: { hp: 60, attack: 40, defense: 50, sp_attack: 75, sp_defense: 85, speed: 95 }, abilities: ['Minus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/312.png' },
  'volbeat': { dex_number: 313, types: ['Bug'], base_stats: { hp: 65, attack: 73, defense: 75, sp_attack: 47, sp_defense: 85, speed: 85 }, abilities: ['Swarm'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/313.png' },
  'illumise': { dex_number: 314, types: ['Bug'], base_stats: { hp: 65, attack: 47, defense: 75, sp_attack: 73, sp_defense: 85, speed: 85 }, abilities: ['Oblivious'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/314.png' },
  'roselia': { dex_number: 315, types: ['Grass', 'Poison'], base_stats: { hp: 50, attack: 60, defense: 45, sp_attack: 100, sp_defense: 80, speed: 65 }, abilities: ['Natural Cure', 'Poison Point'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/315.png' },
  'gulpin': { dex_number: 316, types: ['Poison'], base_stats: { hp: 70, attack: 43, defense: 53, sp_attack: 43, sp_defense: 53, speed: 40 }, abilities: ['Liquid Ooze', 'Sticky Hold'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/316.png' },
  'swalot': { dex_number: 317, types: ['Poison'], base_stats: { hp: 100, attack: 73, defense: 83, sp_attack: 73, sp_defense: 83, speed: 55 }, abilities: ['Liquid Ooze', 'Sticky Hold'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/317.png' },
  'carvanha': { dex_number: 318, types: ['Water', 'Dark'], base_stats: { hp: 45, attack: 90, defense: 20, sp_attack: 65, sp_defense: 20, speed: 65 }, abilities: ['Rough Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/318.png' },
  'sharpedo': { dex_number: 319, types: ['Water', 'Dark'], base_stats: { hp: 70, attack: 120, defense: 40, sp_attack: 95, sp_defense: 40, speed: 95 }, abilities: ['Rough Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/319.png' },
  'wailmer': { dex_number: 320, types: ['Water'], base_stats: { hp: 130, attack: 70, defense: 35, sp_attack: 70, sp_defense: 35, speed: 60 }, abilities: ['Water Veil', 'Oblivious'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/320.png' },
  'wailord': { dex_number: 321, types: ['Water'], base_stats: { hp: 170, attack: 90, defense: 45, sp_attack: 90, sp_defense: 45, speed: 60 }, abilities: ['Water Veil', 'Oblivious'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/321.png' },
  'numel': { dex_number: 322, types: ['Fire', 'Ground'], base_stats: { hp: 60, attack: 60, defense: 40, sp_attack: 65, sp_defense: 45, speed: 35 }, abilities: ['Oblivious'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/322.png' },
  'camerupt': { dex_number: 323, types: ['Fire', 'Ground'], base_stats: { hp: 70, attack: 100, defense: 70, sp_attack: 105, sp_defense: 75, speed: 40 }, abilities: ['Magma Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/323.png' },
  'torkoal': { dex_number: 324, types: ['Fire'], base_stats: { hp: 70, attack: 85, defense: 140, sp_attack: 85, sp_defense: 70, speed: 20 }, abilities: ['White Smoke'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/324.png' },
  'spoink': { dex_number: 325, types: ['Psychic'], base_stats: { hp: 60, attack: 25, defense: 35, sp_attack: 70, sp_defense: 80, speed: 60 }, abilities: ['Thick Fat', 'Own Tempo'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/325.png' },
  'grumpig': { dex_number: 326, types: ['Psychic'], base_stats: { hp: 80, attack: 45, defense: 65, sp_attack: 90, sp_defense: 110, speed: 80 }, abilities: ['Thick Fat', 'Own Tempo'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/326.png' },
  'spinda': { dex_number: 327, types: ['Normal'], base_stats: { hp: 60, attack: 60, defense: 60, sp_attack: 60, sp_defense: 60, speed: 60 }, abilities: ['Own Tempo'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/327.png' },
  'trapinch': { dex_number: 328, types: ['Ground'], base_stats: { hp: 45, attack: 100, defense: 45, sp_attack: 45, sp_defense: 45, speed: 10 }, abilities: ['Hyper Cutter', 'Arena Trap'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/328.png' },
  'vibrava': { dex_number: 329, types: ['Ground', 'Dragon'], base_stats: { hp: 50, attack: 70, defense: 50, sp_attack: 50, sp_defense: 50, speed: 70 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/329.png' },
  'flygon': { dex_number: 330, types: ['Ground', 'Dragon'], base_stats: { hp: 80, attack: 100, defense: 80, sp_attack: 80, sp_defense: 80, speed: 100 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/330.png' },
  'cacnea': { dex_number: 331, types: ['Grass'], base_stats: { hp: 50, attack: 85, defense: 40, sp_attack: 85, sp_defense: 40, speed: 35 }, abilities: ['Sand Veil'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/331.png' },
  'cacturne': { dex_number: 332, types: ['Grass', 'Dark'], base_stats: { hp: 70, attack: 115, defense: 60, sp_attack: 115, sp_defense: 60, speed: 55 }, abilities: ['Sand Veil'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/332.png' },
  'swablu': { dex_number: 333, types: ['Normal', 'Flying'], base_stats: { hp: 45, attack: 40, defense: 60, sp_attack: 40, sp_defense: 75, speed: 50 }, abilities: ['Natural Cure'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/333.png' },
  'altaria': { dex_number: 334, types: ['Dragon', 'Flying'], base_stats: { hp: 75, attack: 70, defense: 90, sp_attack: 70, sp_defense: 105, speed: 80 }, abilities: ['Natural Cure'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/334.png' },
  'zangoose': { dex_number: 335, types: ['Normal'], base_stats: { hp: 73, attack: 115, defense: 60, sp_attack: 60, sp_defense: 60, speed: 90 }, abilities: ['Immunity'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/335.png' },
  'seviper': { dex_number: 336, types: ['Poison'], base_stats: { hp: 73, attack: 100, defense: 60, sp_attack: 100, sp_defense: 60, speed: 65 }, abilities: ['Shed Skin'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/336.png' },
  'lunatone': { dex_number: 337, types: ['Rock', 'Psychic'], base_stats: { hp: 90, attack: 55, defense: 65, sp_attack: 95, sp_defense: 85, speed: 70 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/337.png' },
  'solrock': { dex_number: 338, types: ['Rock', 'Psychic'], base_stats: { hp: 90, attack: 95, defense: 85, sp_attack: 55, sp_defense: 65, speed: 70 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/338.png' },
  'barboach': { dex_number: 339, types: ['Water', 'Ground'], base_stats: { hp: 50, attack: 48, defense: 43, sp_attack: 46, sp_defense: 41, speed: 60 }, abilities: ['Oblivious'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/339.png' },
  'whiscash': { dex_number: 340, types: ['Water', 'Ground'], base_stats: { hp: 110, attack: 78, defense: 73, sp_attack: 76, sp_defense: 71, speed: 60 }, abilities: ['Oblivious'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/340.png' },
  'corphish': { dex_number: 341, types: ['Water'], base_stats: { hp: 43, attack: 80, defense: 65, sp_attack: 50, sp_defense: 35, speed: 35 }, abilities: ['Hyper Cutter', 'Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/341.png' },
  'crawdaunt': { dex_number: 342, types: ['Water', 'Dark'], base_stats: { hp: 63, attack: 120, defense: 85, sp_attack: 90, sp_defense: 55, speed: 55 }, abilities: ['Hyper Cutter', 'Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/342.png' },
  'baltoy': { dex_number: 343, types: ['Ground', 'Psychic'], base_stats: { hp: 40, attack: 40, defense: 55, sp_attack: 40, sp_defense: 70, speed: 55 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/343.png' },
  'claydol': { dex_number: 344, types: ['Ground', 'Psychic'], base_stats: { hp: 60, attack: 70, defense: 105, sp_attack: 70, sp_defense: 120, speed: 75 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/344.png' },
  'lileep': { dex_number: 345, types: ['Rock', 'Grass'], base_stats: { hp: 66, attack: 41, defense: 77, sp_attack: 61, sp_defense: 87, speed: 23 }, abilities: ['Suction Cups'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/345.png' },
  'cradily': { dex_number: 346, types: ['Rock', 'Grass'], base_stats: { hp: 86, attack: 81, defense: 97, sp_attack: 81, sp_defense: 107, speed: 43 }, abilities: ['Suction Cups'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/346.png' },
  'anorith': { dex_number: 347, types: ['Rock', 'Bug'], base_stats: { hp: 45, attack: 95, defense: 50, sp_attack: 40, sp_defense: 50, speed: 75 }, abilities: ['Battle Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/347.png' },
  'armaldo': { dex_number: 348, types: ['Rock', 'Bug'], base_stats: { hp: 75, attack: 125, defense: 100, sp_attack: 70, sp_defense: 80, speed: 45 }, abilities: ['Battle Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/348.png' },
  'feebas': { dex_number: 349, types: ['Water'], base_stats: { hp: 20, attack: 15, defense: 20, sp_attack: 10, sp_defense: 55, speed: 80 }, abilities: ['Swift Swim'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/349.png' },
  'milotic': { dex_number: 350, types: ['Water'], base_stats: { hp: 95, attack: 60, defense: 79, sp_attack: 100, sp_defense: 125, speed: 81 }, abilities: ['Marvel Scale'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/350.png' },
  'castform': { dex_number: 351, types: ['Normal'], base_stats: { hp: 70, attack: 70, defense: 70, sp_attack: 70, sp_defense: 70, speed: 70 }, abilities: ['Forecast'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/351.png' },
  'kecleon': { dex_number: 352, types: ['Normal'], base_stats: { hp: 60, attack: 90, defense: 70, sp_attack: 60, sp_defense: 120, speed: 40 }, abilities: ['Color Change'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/352.png' },
  'shuppet': { dex_number: 353, types: ['Ghost'], base_stats: { hp: 44, attack: 75, defense: 35, sp_attack: 63, sp_defense: 33, speed: 45 }, abilities: ['Insomnia'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/353.png' },
  'banette': { dex_number: 354, types: ['Ghost'], base_stats: { hp: 64, attack: 115, defense: 65, sp_attack: 83, sp_defense: 63, speed: 65 }, abilities: ['Insomnia'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/354.png' },
  'duskull': { dex_number: 355, types: ['Ghost'], base_stats: { hp: 20, attack: 40, defense: 90, sp_attack: 30, sp_defense: 90, speed: 25 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/355.png' },
  'dusclops': { dex_number: 356, types: ['Ghost'], base_stats: { hp: 40, attack: 70, defense: 130, sp_attack: 60, sp_defense: 130, speed: 25 }, abilities: ['Pressure'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/356.png' },
  'tropius': { dex_number: 357, types: ['Grass', 'Flying'], base_stats: { hp: 99, attack: 68, defense: 83, sp_attack: 72, sp_defense: 87, speed: 51 }, abilities: ['Chlorophyll'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/357.png' },
  'chimecho': { dex_number: 358, types: ['Psychic'], base_stats: { hp: 75, attack: 50, defense: 80, sp_attack: 95, sp_defense: 90, speed: 65 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/358.png' },
  'absol': { dex_number: 359, types: ['Dark'], base_stats: { hp: 65, attack: 130, defense: 60, sp_attack: 75, sp_defense: 60, speed: 75 }, abilities: ['Pressure'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/359.png' },
  'wynaut': { dex_number: 360, types: ['Psychic'], base_stats: { hp: 95, attack: 23, defense: 48, sp_attack: 23, sp_defense: 48, speed: 23 }, abilities: ['Shadow Tag'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/360.png' },
  'snorunt': { dex_number: 361, types: ['Ice'], base_stats: { hp: 50, attack: 50, defense: 50, sp_attack: 50, sp_defense: 50, speed: 50 }, abilities: ['Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/361.png' },
  'glalie': { dex_number: 362, types: ['Ice'], base_stats: { hp: 80, attack: 80, defense: 80, sp_attack: 80, sp_defense: 80, speed: 80 }, abilities: ['Inner Focus'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/362.png' },
  'spheal': { dex_number: 363, types: ['Ice', 'Water'], base_stats: { hp: 70, attack: 40, defense: 50, sp_attack: 55, sp_defense: 50, speed: 25 }, abilities: ['Thick Fat'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/363.png' },
  'sealeo': { dex_number: 364, types: ['Ice', 'Water'], base_stats: { hp: 90, attack: 60, defense: 70, sp_attack: 75, sp_defense: 70, speed: 45 }, abilities: ['Thick Fat'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/364.png' },
  'walrein': { dex_number: 365, types: ['Ice', 'Water'], base_stats: { hp: 110, attack: 80, defense: 90, sp_attack: 95, sp_defense: 90, speed: 65 }, abilities: ['Thick Fat'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/365.png' },
  'clamperl': { dex_number: 366, types: ['Water'], base_stats: { hp: 35, attack: 64, defense: 85, sp_attack: 74, sp_defense: 55, speed: 32 }, abilities: ['Shell Armor'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/366.png' },
  'huntail': { dex_number: 367, types: ['Water'], base_stats: { hp: 55, attack: 104, defense: 105, sp_attack: 94, sp_defense: 75, speed: 52 }, abilities: ['Swift Swim'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/367.png' },
  'gorebyss': { dex_number: 368, types: ['Water'], base_stats: { hp: 55, attack: 84, defense: 105, sp_attack: 114, sp_defense: 75, speed: 52 }, abilities: ['Swift Swim'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/368.png' },
  'relicanth': { dex_number: 369, types: ['Water', 'Rock'], base_stats: { hp: 100, attack: 90, defense: 130, sp_attack: 45, sp_defense: 65, speed: 55 }, abilities: ['Swift Swim', 'Rock Head'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/369.png' },
  'luvdisc': { dex_number: 370, types: ['Water'], base_stats: { hp: 43, attack: 30, defense: 55, sp_attack: 40, sp_defense: 65, speed: 97 }, abilities: ['Swift Swim'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/370.png' },
  'bagon': { dex_number: 371, types: ['Dragon'], base_stats: { hp: 45, attack: 75, defense: 60, sp_attack: 40, sp_defense: 30, speed: 50 }, abilities: ['Rock Head'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/371.png' },
  'shelgon': { dex_number: 372, types: ['Dragon'], base_stats: { hp: 65, attack: 95, defense: 100, sp_attack: 60, sp_defense: 50, speed: 50 }, abilities: ['Rock Head'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/372.png' },
  'salamence': { dex_number: 373, types: ['Dragon', 'Flying'], base_stats: { hp: 95, attack: 135, defense: 80, sp_attack: 110, sp_defense: 80, speed: 100 }, abilities: ['Intimidate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/373.png' },
  'beldum': { dex_number: 374, types: ['Steel', 'Psychic'], base_stats: { hp: 40, attack: 55, defense: 80, sp_attack: 35, sp_defense: 60, speed: 30 }, abilities: ['Clear Body'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/374.png' },
  'metang': { dex_number: 375, types: ['Steel', 'Psychic'], base_stats: { hp: 60, attack: 75, defense: 100, sp_attack: 55, sp_defense: 80, speed: 50 }, abilities: ['Clear Body'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/375.png' },
  'metagross': { dex_number: 376, types: ['Steel', 'Psychic'], base_stats: { hp: 80, attack: 135, defense: 130, sp_attack: 95, sp_defense: 90, speed: 70 }, abilities: ['Clear Body'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/376.png' },
  'latias': { dex_number: 380, types: ['Dragon', 'Psychic'], base_stats: { hp: 80, attack: 80, defense: 90, sp_attack: 110, sp_defense: 130, speed: 110 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/380.png' },
  'latios': { dex_number: 381, types: ['Dragon', 'Psychic'], base_stats: { hp: 80, attack: 90, defense: 80, sp_attack: 130, sp_defense: 110, speed: 110 }, abilities: ['Levitate'], sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/381.png' },
};

// === POKEMON MOVES DATA ===
// A selection of moves with level-up data for demonstration purposes.
export const movesData = [
  { dex_number: 1, moves: [{ name: "Tackle", level: 1 }, { name: "Growl", level: 1 }, { name: "Leech Seed", level: 7 }, { name: "Vine Whip", level: 10 }, { name: "Poison Powder", level: 15 }, { name: "Razor Leaf", level: 22 }] },
  { dex_number: 4, moves: [{ name: "Scratch", level: 1 }, { name: "Growl", level: 1 }, { name: "Ember", level: 7 }, { name: "Smokescreen", level: 13 }, { name: "Dragon Rage", level: 16 }, { name: "Flamethrower", level: 34 }] },
  { dex_number: 7, moves: [{ name: "Tackle", level: 1 }, { name: "Tail Whip", level: 4 }, { name: "Bubble", level: 7 }, { name: "Water Gun", level: 13 }, { name: "Bite", level: 18 }, { name: "Hydro Pump", level: 42 }] },
  { dex_number: 25, moves: [{ name: "Thunder Shock", level: 1 }, { name: "Growl", level: 1 }, { name: "Quick Attack", level: 11 }, { name: "Double Team", level: 15 }, { name: "Thunderbolt", level: 26 }, { name: "Thunder", level: 41 }] },
  { dex_number: 74, moves: [{ name: "Tackle", level: 1 }, { name: "Defense Curl", level: 6 }, { name: "Rock Throw", level: 11 }, { name: "Magnitude", level: 16 }, { name: "Rock Slide", level: 29 }, { name: "Earthquake", level: 36 }] },
  { dex_number: 76, moves: [{ name: "Tackle", level: 1 }, { name: "Defense Curl", level: 6 }, { name: "Rock Throw", level: 11 }, { name: "Magnitude", level: 16 }, { name: "Rock Slide", level: 29 }, { name: "Earthquake", level: 36 }, { name: "Explosion", level: 43 }] },
  { dex_number: 65, moves: [{ name: "Teleport", level: 1 }, { name: "Confusion", level: 16 }, { name: "Disable", level: 20 }, { name: "Psybeam", level: 27 }, { name: "Recover", level: 31 }, { name: "Psychic", level: 38 }] },
  { dex_number: 68, moves: [{ name: "Low Kick", level: 1 }, { name: "Leer", level: 7 }, { name: "Focus Energy", level: 13 }, { name: "Karate Chop", level: 19 }, { name: "Cross Chop", level: 43 }] },
  { dex_number: 94, moves: [{ name: "Hypnosis", level: 1 }, { name: "Lick", level: 1 }, { name: "Spite", level: 8 }, { name: "Curse", level: 16 }, { name: "Night Shade", level: 25 }, { name: "Shadow Ball", level: 39 }] },
  { dex_number: 373, moves: [{ name: "Rage", level: 1 }, { name: "Ember", level: 10 }, { name: "Headbutt", level: 20 }, { name: "Dragon Breath", level: 30 }, { name: "Fly", level: 50 }, { name: "Dragon Claw", level: 55 }] },
  { dex_number: 376, moves: [{ name: "Take Down", level: 1 }, { name: "Confusion", level: 20 }, { name: "Metal Claw", level: 20 }, { name: "Pursuit", level: 30 }, { name: "Psychic", level: 45 }, { name: "Meteor Mash", level: 50 }] },
  { dex_number: 282, moves: [{ name: "Growl", level: 1 }, { name: "Confusion", level: 6 }, { name: "Double Team", level: 10 }, { name: "Teleport", level: 12 }, { name: "Calm Mind", level: 21 }, { name: "Psychic", level: 26 }, { name: "Future Sight", level: 51 }] },
  { dex_number: 272, moves: [{ name: "Astonish", level: 1 }, { name: "Growl", level: 1 }, { name: "Absorb", level: 1 }, { name: "Nature Power", level: 1 }, { name: "Mega Drain", level: 19 }, { name: "Rain Dance", level: 31 }, { name: "Hydro Pump", level: 49 }] },
  { dex_number: 260, moves: [{ name: "Tackle", level: 1 }, { name: "Growl", level: 1 }, { name: "Mud-Slap", level: 6 }, { name: "Water Gun", level: 10 }, { name: "Take Down", level: 20 }, { name: "Muddy Water", level: 28 }, { name: "Earthquake", level: 52 }] },
  { dex_number: 257, moves: [{ name: "Scratch", level: 1 }, { name: "Growl", level: 1 }, { name: "Ember", level: 7 }, { name: "Double Kick", level: 16 }, { name: "Bulk Up", level: 28 }, { name: "Blaze Kick", level: 36 }, { name: "Sky Uppercut", level: 42 }] },
  { dex_number: 254, moves: [{ name: "Pound", level: 1 }, { name: "Leer", level: 1 }, { name: "Absorb", level: 6 }, { name: "Quick Attack", level: 11 }, { name: "Leaf Blade", level: 29 }, { name: "Slam", level: 43 }, { name: "Detect", level: 17 }] },
  { dex_number: 19, moves: [{ name: "Tackle", level: 1 }, { name: "Tail Whip", level: 1 }, { name: "Quick Attack", level: 7 }, { name: "Hyper Fang", level: 13 }] },
  { dex_number: 16, moves: [{ name: "Tackle", level: 1 }, { name: "Sand Attack", level: 5 }, { name: "Gust", level: 9 }, { name: "Quick Attack", level: 13 }] },
  { dex_number: 43, moves: [{ name: "Absorb", level: 1 }, { name: "Sweet Scent", level: 7 }, { name: "Poison Powder", level: 14 }] },
  { dex_number: 13, moves: [{ name: "Poison Sting", level: 1 }, { name: "String Shot", level: 1 }] },
  { dex_number: 129, moves: [{ name: "Splash", level: 1 }, { name: "Tackle", level: 15 }] },
  { dex_number: 27, moves: [{ name: "Scratch", level: 1 }, { name: "Defense Curl", level: 6 }, { name: "Sand Attack", level: 10 }] },
  { dex_number: 261, moves: [{ name: "Tackle", level: 1 }, { name: "Howl", level: 5 }, { name: "Sand Attack", level: 9 }, { name: "Bite", level: 13 }] },
  { dex_number: 276, moves: [{ name: "Peck", level: 1 }, { name: "Growl", level: 4 }, { name: "Focus Energy", level: 8 }, { name: "Quick Attack", level: 13 }] },
  { dex_number: 263, moves: [{ name: "Tackle", level: 1 }, { name: "Growl", level: 1 }, { name: "Tail Whip", level: 5 }, { name: "Headbutt", level: 9 }] },
  { dex_number: 270, moves: [{ name: "Astonish", level: 1 }, { name: "Growl", level: 3 }, { name: "Absorb", level: 5 }, { name: "Bubble", level: 7 }] },
  { dex_number: 322, moves: [{ name: "Growl", level: 1 }, { name: "Tackle", level: 1 }, { name: "Ember", level: 8 }, { name: "Magnitude", level: 15 }] },
  { dex_number: 309, moves: [{ name: "Tackle", level: 1 }, { name: "Thunder Wave", level: 4 }, { name: "Quick Attack", level: 9 }, { name: "Spark", level: 12 }] },
  { dex_number: 299, moves: [{ name: "Tackle", level: 1 }, { name: "Harden", level: 7 }, { name: "Rock Throw", level: 13 }, { name: "Block", level: 16 }] }
];

// === EXAMPLE TRAINER DATA ===
// This comprehensive list is used by the AI to understand how to build good trainers.
export const gbaTrainerDataset = `
[
  {
    "name": "Rival May (Route 103)",
    "class": "Rival",
    "difficulty": "Easy",
    "theme": "Starter",
    "party": [
      { "species": "Treecko", "level": 5, "item": "None", "moves": ["Pound", "Leer"], "role": "Starter" }
    ]
  },
  {
    "name": "Gym Leader Roxanne",
    "class": "Gym Leader",
    "difficulty": "Medium",
    "theme": "Rock-type",
    "party": [
      { "species": "Geodude", "level": 12, "item": "None", "moves": ["Tackle", "Defense Curl", "Rock Throw"], "role": "Physical Wall" },
      { "species": "Nosepass", "level": 15, "item": "Sitrus Berry", "moves": ["Tackle", "Harden", "Rock Tomb", "Rock Throw"], "role": "Ace/Defensive Pivot" }
    ]
  },
  {
    "name": "Ace Trainer Kirk (Route 116)",
    "class": "Ace Trainer",
    "difficulty": "Medium",
    "theme": "Balanced",
    "party": [
      { "species": "Electrike", "level": 14, "moves": ["Quick Attack", "Thunder Wave", "Spark"], "role": "Fast Special Attacker" },
      { "species": "Taillow", "level": 14, "moves": ["Peck", "Quick Attack", "Wing Attack"], "role": "Fast Physical Attacker" }
    ]
  },
  {
    "name": "Winstrate Victoria",
    "class": "Family",
    "difficulty": "Medium",
    "theme": "Weather (Rain)",
    "party": [
      { "species": "Lombre", "level": 18, "item": "None", "moves": ["Astonish", "Fake Out", "Nature Power"], "role": "Mixed Attacker" }
    ]
  },
  {
    "name": "Gym Leader Wattson",
    "class": "Gym Leader",
    "difficulty": "Medium-Hard",
    "theme": "Electric-type, Paralysis",
    "party": [
      { "species": "Voltorb", "level": 20, "moves": ["Rollout", "Spark", "Self-Destruct"], "role": "Fast Physical/Suicide Lead" },
      { "species": "Electrike", "level": 20, "moves": ["Quick Attack", "Thunder Wave", "Shock Wave"], "role": "Fast Special Attacker" },
      { "species": "Magneton", "level": 22, "moves": ["Thunder Wave", "Thunderbolt", "Supersonic"], "role": "Bulky Special Attacker" },
      { "species": "Manectric", "level": 24, "item": "Sitrus Berry", "moves": ["Quick Attack", "Thunder Wave", "Shock Wave", "Howl"], "role": "Ace/Fast Special Attacker" }
    ]
  },
  {
    "name": "Expert Timothy (Mt. Chimney)",
    "class": "Expert",
    "difficulty": "Hard",
    "theme": "Fighting-type",
    "party": [
      { "species": "Hariyama", "level": 27, "item": "None", "moves": ["Vital Throw", "Arm Thrust", "Seismic Toss", "Smelling Salts"], "role": "Bulky Physical Attacker" }
    ]
  },
  {
    "name": "Gym Leader Flannery",
    "class": "Gym Leader",
    "difficulty": "Hard",
    "theme": "Fire-type, Burn/Overheat",
    "party": [
      { "species": "Numel", "level": 24, "moves": ["Tackle", "Ember", "Magnitude"], "role": "Mixed Attacker" },
      { "species": "Slugma", "level": 24, "moves": ["Smog", "Rock Throw", "Overheat"], "role": "Special Attacker" },
      { "species": "Camerupt", "level": 26, "moves": ["Ember", "Tackle", "Focus Energy", "Overheat"], "role": "Bulky Special Attacker" },
      { "species": "Torkoal", "level": 29, "item": "White Herb", "moves": ["Body Slam", "Flamethrower", "Attract", "Overheat"], "role": "Ace/Defensive Wall" }
    ]
  },
  {
    "name": "Cooltrainer Brooke (Jagged Pass)",
    "class": "Ace Trainer",
    "difficulty": "Hard",
    "theme": "Momentum (VoltTurn)",
    "party": [
        { "species": "Wingull", "level": 21, "moves": ["Wing Attack", "Water Gun"], "role": "Scout" },
        { "species": "Numel", "level": 21, "moves": ["Ember", "Magnitude"], "role": "Mixed Attacker" },
        { "species": "Roselia", "level": 21, "moves": ["Mega Drain", "Leech Seed"], "role": "Special Attacker/Support" }
    ]
  },
  {
    "name": "Rival Brendan (Route 119)",
    "class": "Rival",
    "difficulty": "Hard",
    "theme": "Balanced, Evolved",
    "party": [
      { "species": "Swellow", "level": 29, "moves": ["Wing Attack", "Quick Attack", "Double Team"], "role": "Fast Physical Attacker" },
      { "species": "Wailmer", "level": 29, "moves": ["Water Pulse", "Rollout", "Whirlpool"], "role": "Bulky Special Attacker" },
      { "species": "Combusken", "level": 31, "item": "Sitrus Berry", "moves": ["Double Kick", "Peck", "Ember", "Bulk Up"], "role": "Ace/Mixed Attacker" }
    ]
  },
  {
    "name": "Gym Leader Winona",
    "class": "Gym Leader",
    "difficulty": "Very Hard",
    "theme": "Flying-type, Hyper Beam",
    "party": [
      { "species": "Swablu", "level": 29, "moves": ["Perish Song", "Mirror Move", "Safeguard"], "role": "Annoyer/Support" },
      { "species": "Tropius", "level": 29, "moves": ["Sunny Day", "Aerial Ace", "Solar Beam"], "role": "Weather Sweeper" },
      { "species": "Pelipper", "level": 30, "moves": ["Water Gun", "Supersonic", "Protect", "Aerial Ace"], "role": "Defensive Pivot" },
      { "species": "Skarmory", "level": 31, "moves": ["Sandstorm", "Air Cutter", "Steel Wing", "Aerial Ace"], "role": "Physical Wall" },
      { "species": "Altaria", "level": 33, "item": "Oran Berry", "moves": ["Earthquake", "Dragon Breath", "Dragon Dance", "Aerial Ace"], "role": "Ace/Dragon Dance Sweeper" }
    ]
  },
  {
    "name": "Elite Four Sidney",
    "class": "Elite Four",
    "difficulty": "Expert",
    "theme": "Dark-type, Physical Offense",
    "party": [
      { "species": "Mightyena", "level": 46, "moves": ["Take Down", "Crunch", "Sand Attack"], "role": "Lead/Intimidate user (in double battles)" },
      { "species": "Shiftry", "level": 48, "moves": ["Fake Out", "Double Team", "Extrasensory"], "role": "Mixed Attacker" },
      { "species": "Cacturne", "level": 46, "moves": ["Leech Seed", "Faint Attack", "Needle Arm"], "role": "Stall/Physical Attacker" },
      { "species": "Crawdaunt", "level": 48, "moves": ["Surf", "Swords Dance", "Facade", "Crunch"], "role": "Swords Dance Sweeper" },
      { "species": "Absol", "level": 49, "item": "Sitrus Berry", "moves": ["Aerial Ace", "Swords Dance", "Slash", "Snatch"], "role": "Ace/Physical Sweeper" }
    ]
  },
  {
    "name": "Elite Four Phoebe",
    "class": "Elite Four",
    "difficulty": "Expert",
    "theme": "Ghost-type, Status/Disruption",
    "party": [
      { "species": "Dusclops", "level": 48, "moves": ["Shadow Punch", "Confuse Ray", "Curse", "Protect"], "role": "Defensive Wall/Disruptor" },
      { "species": "Banette", "level": 49, "moves": ["Shadow Ball", "Will-O-Wisp", "Faint Attack", "Psychic"], "role": "Special Attacker" },
      { "species": "Sableye", "level": 50, "moves": ["Shadow Ball", "Double Team", "Night Shade", "Faint Attack"], "role": "Annoyer (No Weaknesses)" },
      { "species": "Banette", "level": 49, "moves": ["Shadow Ball", "Toxic", "Skill Swap", "Grudge"], "role": "Status Spreader" },
      { "species": "Dusclops", "level": 51, "item": "Sitrus Berry", "moves": ["Shadow Ball", "Ice Beam", "Rock Slide", "Earthquake"], "role": "Ace/Mixed Wallbreaker" }
    ]
  },
  {
    "name": "Champion Wallace",
    "class": "Champion",
    "difficulty": "Master",
    "theme": "Water-type, Balanced",
    "party": [
      { "species": "Wailord", "level": 57, "moves": ["Rain Dance", "Water Spout", "Double-Edge", "Blizzard"], "role": "Lead/Special Tank" },
      { "species": "Tentacruel", "level": 55, "moves": ["Toxic", "Hydro Pump", "Sludge Bomb", "Ice Beam"], "role": "Special Wall/Status" },
      { "species": "Ludicolo", "level": 56, "moves": ["Giga Drain", "Surf", "Double Team", "Leech Seed"], "role": "Rain Sweeper/Stall" },
      { "species": "Whiscash", "level": 56, "moves": ["Surf", "Earthquake", "Amnesia", "Hyper Beam"], "role": "Bulky Mixed Attacker" },
      { "species": "Gyarados", "level": 56, "moves": ["Surf", "Earthquake", "Hyper Beam", "Dragon Dance"], "role": "Physical Sweeper" },
      { "species": "Milotic", "level": 58, "item": "Sitrus Berry", "moves": ["Surf", "Ice Beam", "Recover", "Toxic"], "role": "Ace/Special Wall/Sweeper" }
    ]
  }
]
`;
