export const labAssistantPrompts = [
  "Design a gym leader who uses environmental hazards",
  "Create a trainer whose team tells a story",
  "Build an Elite Four member obsessed with evolution",
  "Design a Battle Frontier specialist with unique rules",
  "Craft a wandering trainer who appears randomly",
  "Create a doubles expert with perfect synergy",
  "Design a trainer who only uses baby Pokemon",
  "Build a mysterious masked challenger",
  "Write a mystery involving legendary artifacts",
  "Create a subplot about Pokemon consciousness",
  "Design a festival that reveals ancient secrets",
  "Craft a political conspiracy in the Pokemon League",
  "Write a time loop scenario in a Pokecenter",
  "Design a quest involving Pokemon language",
  "Craft a tale of two regions at war",
  "Write a ghost story set in Lavender Town",
  "Design a team around weather control",
  "Create the ultimate stall strategy",
  "Build a team of misfits that work perfectly",
  "Design a hyper-offensive glass cannon team",
  "Design a hidden city accessible only by Surf",
  "Create a dungeon that changes with the tides",
  "Craft a secret laboratory beneath a Pokecenter",
  "Design a floating island in the clouds",
  "Create a professor studying Pokemon emotions",
  "Design twins with opposite philosophies",
  "Craft a former champion turned hermit",
  "Create a merchant selling impossible items",
];